import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../providers/language_provider.dart';

class AppLocalizations {
  static final Map<String, Map<String, String>> _localizedValues = {
    'vi': {
      'appName': 'Smart Note',
      'settingsTitle': 'Cài đặt',
      'darkModeTitle': 'Giao diện tối',
      'darkModeSubtitle': 'Thay đổi giao diện sáng hoặc tối cho ứng dụng',
      'languageTitle': 'Ngôn ngữ',
      'languageSubtitle': 'Lựa chọn ngôn ngữ hiển thị hệ thống',
      'biometricLockTitle': 'Khóa ghi chú bằng sinh trắc học',
      'biometricLockSubtitle': 'Sử dụng Vân tay hoặc Khuôn mặt để mở ghi chú',
      'biometricNotAvailable': 'Thiết bị không hỗ trợ sinh trắc học',
      'biometricNotEnrolled': 'Vui lòng đăng ký vân tay trong Cài đặt thiết bị',
      'biometricAuthFailed': 'Xác thực thất bại. Thử lại?',
      'biometricAuthSuccess': 'Xác thực thành công',
      'biometricPromptReason': 'Xác thực để mở ghi chú',
      'biometricLockedOut': 'Sinh trắc học bị tạm khóa do thử sai nhiều lần',
      'biometricPermanentlyLockedOut': 'Sinh trắc học bị khóa vĩnh viễn. Vui lòng mở khóa bằng mã PIN',
      'biometricUnknownError': 'Có lỗi xảy ra khi xác thực sinh trắc học',
      'featureInDevelopment': 'Tính năng đang phát triển',
      'notificationsTitle': 'Thông báo',
      'notificationsSubtitle': 'Quản lý thông báo và nhắc nhở',
      'helpTitle': 'Trợ giúp',
      'helpSubtitle': 'Hướng dẫn sử dụng và FAQ',
      'aboutTitle': 'Về ứng dụng',
      'aboutSubtitle': 'Phiên bản 1.0.0',
      'aboutDesc': 'Ứng dụng ghi chú thông minh cao cấp được phát triển bởi đội ngũ Smart Note. Toàn bộ dữ liệu được bảo mật và đồng bộ hóa đám mây an toàn.',
      'close': 'Đóng',
      'alertOk': 'Đồng ý',
      'alertCancel': 'Hủy',
      'toastThemeDark': 'Đã chuyển sang giao diện tối',
      'toastThemeLight': 'Đã chuyển sang giao diện sáng',
      'emptyHomeTitle': 'Chưa có ghi chú nào',
      'emptyHomeSubtitle': 'Nhấn + để tạo ghi chú đầu tiên',
      'emptyArchiveTitle': 'Kho lưu trữ trống',
      'emptyArchiveSubtitle': 'Các ghi chú được lưu trữ sẽ hiển thị ở đây',
      'emptyTrashTitle': 'Thùng rác trống',
      'emptyTrashSubtitle': 'Ghi chú trong thùng rác sẽ tự xóa sau 7 ngày',
      'emptySearchTitle': 'Không tìm thấy kết quả',
      'emptySearchSubtitle': 'Thử từ khóa khác',
      'emptySearchAction': 'Xóa bộ lọc',
      'languageSelectTitle': 'Chọn ngôn ngữ',
      'notSetBiometricTitle': 'Chưa thiết lập sinh trắc học',
      'notSetBiometricDesc': 'Bạn cần thêm vân tay hoặc khuôn mặt trong cài đặt điện thoại để sử dụng tính năng khóa ghi chú.',
      'notSetBiometricBtnLater': 'Để sau',
      'notSetBiometricBtnOpen': 'Mở cài đặt',
      'settingsBiometricLockTitle': 'Khóa vân tay ứng dụng',
      'toastBiometricEnabled': 'Đã kích hoạt khóa vân tay',
      'toastBiometricDisabled': 'Đã tắt khóa vân tay',
      
      // Drawer
      'drawerNotes': 'Ghi chú',
      'drawerReminders': 'Nhắc nhở',
      'drawerLabels': 'Nhãn',
      'drawerEditLabels': 'Chỉnh sửa',
      'drawerCreateNewLabel': 'Tạo nhãn mới',
      'drawerArchive': 'Lưu trữ',
      'drawerTrash': 'Thùng rác',
      'drawerSettings': 'Cài đặt',

      // Home Screen
      'quickAudio': 'Âm thanh',
      'quickImage': 'Hình ảnh',
      'quickDrawing': 'Bản vẽ',
      'quickList': 'Danh sách',
      'quickText': 'Văn bản',
      'emptyRemindersTitle': 'Không có nhắc nhở',
      'emptyRemindersSubtitle': 'Ghi chú có nhắc nhở sẽ xuất hiện ở đây',
      'emptyLabelTitle': 'Trống',
      'emptyLabelSubtitle': 'Không có ghi chú nào thuộc nhãn này',
      'pinnedSection': 'Được ghim',
      'othersSection': 'Khác',
      'searchPlaceholder': 'Tìm kiếm',
      'searchRemindersPlaceholder': 'Tìm kiếm nhắc nhở',
      'searchInLabelPlaceholder': 'Tìm kiếm trong {label}',
      'cancelSelection': 'Hủy chọn',
      'selectedCount': '{count} đã chọn',
      'changeLabel': 'Thay đổi nhãn dán',
      'pinUnpinBatch': 'Ghim/Bỏ ghim hàng loạt',
      'archive': 'Lưu trữ',
      'moveToTrash': 'Chuyển vào thùng rác',
      'sortUpdatedNewest': 'Đang sắp xếp: Mới chỉnh sửa gần đây',
      'sortCreatedNewest': 'Đang sắp xếp: Mới tạo gần đây',
      'sortTitleAZ': 'Đang sắp xếp: Tiêu đề A → Z',
      'assignLabelTitle': 'Gán nhãn dán',
      'createNewLabelHint': 'Tạo nhãn mới...',
      'createdAndAssignedLabel': 'Đã tạo và gán nhãn "{tag}"',
      'assignedLabel': 'Đã gán nhãn "{tag}"',
      'cancel': 'Hủy',
      'movedNotesToTrash': 'Đã chuyển {count} ghi chú vào thùng rác',
      'undo': 'Hoàn tác',
      'archivedNotesCount': 'Đã lưu trữ {count} ghi chú',

      // Trash Screen
      'deleteForeverTitle': 'Xóa vĩnh viễn?',
      'deleteForeverConfirm': 'Hành động này không thể hoàn tác. Bạn có chắc muốn xóa vĩnh viễn {count} ghi chú đã chọn?',
      'delete': 'Xóa',
      'trashWarning': 'Ghi chú trong Thùng rác sẽ bị xóa tự động sau 7 ngày.',
      'trashTitle': 'Thùng rác',
      'clearTrash': 'Dọn sạch thùng rác',
      'clearTrashInDevelopment': 'Tính năng dọn sạch đang phát triển',
      'restore': 'Khôi phục',
      'deleteForever': 'Xóa vĩnh viễn',
      'restoreNote': 'Khôi phục ghi chú',
      'restoredNote': 'Đã khôi phục ghi chú',
      'deletingCloudNote': 'Đang xóa vĩnh viễn tài liệu đám mây...',

      // Archive Screen
      'restoredNotesCount': 'Đã khôi phục {count} ghi chú',
      'moveToTrashTitle': 'Chuyển vào Thùng rác?',
      'moveToTrashConfirm': 'Bạn có chắc muốn chuyển {count} ghi chú vào Thùng rác không?',
      'archiveTitle': 'Lưu trữ',
      'changeLayout': 'Đổi bố cục',
      'unarchive': 'Bỏ lưu trữ',
      'restoreToHome': 'Khôi phục về Trang chủ',
      'unarchivedNote': 'Đã bỏ lưu trữ ghi chú',

      // Manage Labels Screen
      'editLabelsTitle': 'Chỉnh sửa nhãn',
      'createNewLabel': 'Tạo nhãn mới',

      // Search Screen
      'searchYourNotesHint': 'Tìm kiếm ghi chú của bạn',
      'noteTypeFilter': 'Loại ghi chú',
      'listFilter': 'Danh sách',
      'imageFilter': 'Hình ảnh',
      'audioFilter': 'Âm thanh',
      'urlFilter': 'URL',
      'labelFilter': 'Nhãn dán',
      'statusFilter': 'Trạng thái',
      'foundNotesCount': 'TÌM THẤY {count} GHI CHÚ KHỚP',

      // Editor & Sheets
      'deleteNote': 'Xóa ghi chú',
      'labels': 'Nhãn',
      'exportPdf': 'Xuất file PDF',
      'save': 'Lưu',
      'stay': 'Ở lại',
      'exit': 'Thoát',
      'uploadingFilesTitle': 'Đang tải lên tệp tin',
      'uploadingFilesConfirm': 'Có tệp tin đang được tải lên. Nếu bạn thoát bây giờ, quá trình tải lên sẽ bị hủy và tệp tin sẽ không được lưu. Bạn có chắc chắn muốn thoát?',
      'pdfInitializing': 'Đang khởi tạo tài liệu PDF...',
      'pdfDownloadingImages': 'Đang tải hình ảnh đính kèm...',
      'pdfAttachedImages': 'Hình ảnh đính kèm:',
      'pdfPageCount': 'Trang {page} / {total}',
      'pdfUntitledNote': 'Ghi chú không tiêu đề',
      'pdfExportSuccess': 'Xuất file PDF thành công!',
      'pdfExportError': 'Lỗi khi xuất PDF: {error}',
      'addImage': 'Thêm hình ảnh',
      'addDrawing': 'Bản vẽ',
      'startRecording': 'Ghi âm',
      'stopRecording': 'Dừng ghi âm',
      'addChecklist': 'Danh sách',

      // Editor – upload/delete banners
      'uploadingAudio': 'Đang tải lên âm thanh...',
      'uploadAudioSuccess': 'Tải lên âm thanh thành công!',
      'uploadAudioFail': 'Tải lên âm thanh thất bại.',
      'uploadAudioError': 'Lỗi: Tải lên âm thanh thất bại.',
      'recordFailed': 'Ghi âm thất bại: Không lấy được file audio.',
      'deletingAudio': 'Đang xóa âm thanh khỏi đám mây...',
      'deleteAudioSuccess': 'Đã xóa âm thanh thành công.',
      'deleteAudioFail': 'Xóa âm thanh thất bại.',
      'deletingImage': 'Đang xóa hình ảnh khỏi đám mây...',
      'deleteImageSuccess': 'Đã xóa hình ảnh thành công.',
      'deleteImageFail': 'Xóa hình ảnh thất bại.',
      'uploadImageError': 'Lỗi tải lên hình ảnh',
      'uploadDrawingError': 'Lỗi tải lên bản vẽ',
      'updateDrawingError': 'Lỗi cập nhật bản vẽ',

      // Editor – dialogs & snackbars
      'deleteNoteTitle': 'Xóa ghi chú?',
      'deleteNoteConfirm': 'Ghi chú sẽ được chuyển vào Thùng rác và tự động xóa sau 7 ngày.',
      'archivedNote': 'Đã chuyển vào kho lưu trữ',
      'unarchivedNoteMsg': 'Đã hủy lưu trữ ghi chú',
      'lockedNote': '🔒 Đã khóa ghi chú',
      'unlockedNote': '🔓 Đã mở khóa ghi chú',
      'lockNoteTooltip': 'Khóa ghi chú',
      'unlockNoteTooltip': 'Mở khóa ghi chú',
      'unpinTooltip': 'Bỏ ghim',
      'pinTooltip': 'Ghim',
      'reminderTooltip': 'Nhắc nhở',
      'requiresSaveMsg': 'Vui lòng nhập nội dung để có thể {action} ghi chú này',
      'aiTooltip': 'AI Trợ lý',
      'biometricRetry': 'Thử lại',

      // Editor – reminder sheet
      'reminderSheetTitle': 'Nhắc nhở',
      'scheduledTime': 'Thời gian đã hẹn',
      'todayAt18': 'Hôm nay lúc 18:00',
      'tomorrowAt8': 'Ngày mai lúc 08:00',
      'nextMondayAt8': 'Thứ Hai tuần sau lúc 08:00',
      'pickDateTime': 'Chọn ngày & giờ...',
      'reminderSet': '⏰ Đã hẹn nhắc nhở lúc {time}',
      'reminderCancelled': '🚫 Đã hủy nhắc nhở ghi chú',
      'reminderPastError': '⚠️ Thời gian nhắc nhở không được ở quá khứ!',
      'reminderPrefix': 'Nhắc nhở: {time}',
      'notifPermissionTitle': 'Quyền thông báo bị tắt',
      'notifPermissionDesc': 'Để không bỏ lỡ các nhắc nhở quan trọng của ghi chú, bạn cần cấp quyền thông báo trong cài đặt điện thoại.',
      'notifPermissionLater': 'Để sau',
      'notifPermissionOpen': 'Mở cài đặt',
      'reminderToday': 'Hôm nay, {time}',
      'reminderTomorrow': 'Ngày mai, {time}',

      // Editor – lock screen
      'noteLockedTitle': 'Ghi chú đã được khóa',
      'noteLockedSubtitle': 'Chạm để mở khóa bằng sinh trắc học',
      'authenticateNow': 'Xác thực ngay',

      // Editor – toolbar tooltips
      'toolbarAdd': 'Thêm',
      'toolbarColor': 'Màu sắc',
      'toolbarFormat': 'Định dạng',
      'toolbarUndo': 'Hoàn tác',
      'toolbarRedo': 'Làm lại',
      'toolbarMore': 'Thêm nữa',

      // Editor – image source sheet
      'pickFromGallery': 'Chọn từ thư viện',
      'takePhoto': 'Chụp ảnh',

      // Editor – title & note placeholder
      'titleHint': 'Tiêu đề',
      'notePlaceholder': 'Ghi chú',

      // Editor – image viewer
      'imageCountTitle': '{current} trong số {total}',
      'drawOnImageTooltip': 'Vẽ đè lên ảnh',
      'imageOptionsTooltip': 'Tùy chọn ảnh',
      'duplicateImage': 'Sao chép',
      'deleteImage': 'Xóa ảnh',

      // Editor – label search
      'labelSearchHint': 'Nhập tên nhãn',
      'createLabelOption': 'Tạo "{name}"',

      // AI Assistant
      'aiAssistantTitle': 'AI Trợ lý ghi chú',
      'aiGenerateTitle': 'Tạo tiêu đề',
      'aiGenerateTitleSub': 'Tự động gợi ý tiêu đề từ nội dung ghi chú',
      'aiSummarize': 'Tóm tắt ghi chú',
      'aiSummarizeSub': 'Tạo bản tóm tắt ngắn gọn từ nội dung hiện tại',
      'aiMakeChecklist': 'Chuyển thành checklist',
      'aiMakeChecklistSub': 'Tạo danh sách việc cần làm từ nội dung hiện tại',
      'aiSuggestLabels': 'Gợi ý nhãn',
      'aiSuggestLabelsSub': 'Gợi ý các nhãn phù hợp cho ghi chú',
      'aiNeedContent': 'Hãy nhập nội dung trước khi dùng AI',
      'aiNeedTitleOrContent': 'Hãy nhập tiêu đề hoặc nội dung trước khi dùng AI',
      'aiAlreadyChecklist': 'Ghi chú đã ở dạng checklist',
      'aiNoChecklist': 'AI chưa tạo được checklist hợp lệ',
      'aiCannotInsertInChecklist': 'Không thể chèn tóm tắt khi đang ở checklist',
      'aiProcessing': 'AI đang xử lý...',
      'aiSummaryTitle': 'Tóm tắt ghi chú',
      'aiSummaryInsert': 'Chèn vào ghi chú',
      'aiSummaryInsertText': '\n\nTóm tắt:\n',
      'aiChecklistTitle': 'Checklist từ AI',
      'aiUseChecklist': 'Dùng checklist này',
      'aiTitleSuggestTitle': 'Gợi ý tiêu đề từ AI',
      'aiTitleProposed': 'Tiêu đề đề xuất:',
      'aiUseTitle': 'Dùng tiêu đề này',
      'aiTagsTitle': 'Gợi ý nhãn từ AI',
      'aiTagsDesc': 'AI gợi ý các nhãn sau. Vui lòng chọn nhãn muốn sử dụng:',
      'aiAddLabels': 'Thêm nhãn',
      'aiNetworkError': 'AI cần kết nối mạng. Vui lòng kiểm tra internet và thử lại.',
      'aiOverloadError': 'AI đang quá tải. Vui lòng thử lại sau.',
      'aiPermissionError': 'AI chưa được cấp quyền. Vui lòng kiểm tra cấu hình Firebase.',
      'aiGenericError': 'AI chưa xử lý được yêu cầu này. Vui lòng thử lại.',

      // Drawing Screen
      'drawingBackgroundError': 'Lỗi khi chèn ảnh nền: {error}',
      'selectColorWheel': 'Chọn màu tự do',
      'select': 'Chọn',
      'thickness': 'Đo độ dày nét vẽ: {val} px',
      'colorPalette': 'Bảng màu sắc',
      'drawingSaveConfirmTitle': 'Lưu bản vẽ?',
      'drawingSaveConfirmDesc': 'Bạn có muốn lưu các thay đổi trên bản vẽ này không?',
      'discardExit': 'Hủy bỏ và thoát',
      'keepDrawing': 'Tiếp tục vẽ',
      'saveDrawing': 'Lưu lại',
      'insertBackgroundImage': 'Chèn ảnh nền',
      'paperTemplateStyle': 'Kiểu giấy nền',
      'paperPlain': 'Giấy trơn',
      'paperRuled': 'Giấy kẻ ngang',
      'paperGrid': 'Giấy kẻ ô ly',
      'undoTooltip': 'Hoàn tác',
      'redoTooltip': 'Làm lại',
      
      // Profile Screen & Drawer
      'accountTitle': 'TÀI KHOẢN',
      'profileTitle': 'Tài khoản',
      'displayName': 'Tên hiển thị',
      'bio': 'Tiểu sử',
      'bioHint': 'Viết gì đó về bản thân...',
      'saveChanges': 'Lưu thay đổi',
      'currentPassword': 'Mật khẩu hiện tại',
      'newPasswordHint': 'Mật khẩu mới (tối thiểu 6 ký tự)',
      'confirmNewPasswordHint': 'Xác nhận mật khẩu mới',
      'update': 'Cập nhật',
      'changePassword': 'Đổi mật khẩu',
      'personalInfo': 'Thông tin cá nhân',
      'manageAccountInfo': 'Quản lý thông tin tài khoản',
      'securityTitle': 'Bảo mật',
      'passwordAndAuth': 'Mật khẩu và xác thực',
      'logout': 'Đăng xuất tài khoản',
      'logoutConfirmTitle': 'Đăng xuất?',
      'logoutConfirmDesc': 'Bạn có chắc muốn đăng xuất không?',
      'userName': 'Người dùng',
      'manageAccountBtn': 'Quản lý tài khoản',
      'nameEmptyError': 'Tên không được để trống',
      'updateNameSuccess': 'Đã cập nhật tên ✓',
      'updateBioSuccess': 'Đã cập nhật tiểu sử ✓',
      'fillAllFieldsError': 'Điền đầy đủ thông tin',
      'passwordLengthError': 'Mật khẩu mới phải có ít nhất 6 ký tự',
      'passwordMismatchError': 'Mật khẩu xác nhận không khớp',
      'passwordChangeSuccess': 'Đổi mật khẩu thành công ✓',
      'oldPasswordIncorrectError': 'Mật khẩu cũ không đúng',
      'avatarUpdateSuccess': 'Đã cập nhật ảnh ✓',
      'uploadError': 'Lỗi upload: {error}',

      // Login & Syncing
      'welcomeBack': 'Chào mừng trở lại!',
      'createNewAccount': 'Tạo tài khoản mới',
      'loginToSync': 'Đăng nhập để tiếp tục đồng bộ ghi chú',
      'startSmartJourney': 'Bắt đầu hành trình ghi chú thông minh của bạn',
      'passwordLabel': 'Mật khẩu',
      'forgotPassword': 'Quên mật khẩu?',
      'orContinueWith': 'Hoặc tiếp tục với',
      'loginWithGoogle': 'Đăng nhập bằng Google',
      'noAccountQuestion': 'Chưa có tài khoản? ',
      'hasAccountQuestion': 'Đã có tài khoản? ',
      'registerNow': 'Đăng ký ngay',
      'loginNow': 'Đăng nhập',
      'networkConnectionError': 'Không có kết nối mạng. Vui lòng kiểm tra lại.',
      'fillEmailPassError': 'Vui lòng nhập đầy đủ Email và Mật khẩu.',
      'syncingTitle': 'Đang đồng bộ dữ liệu',
      'pleaseWait': 'Vui lòng chờ trong giây lát...',
      'syncStepCloud': 'Xác thực kết nối Cloud...',
      'syncStepFetch': 'Đang tải ghi chú từ Firestore...',
      'syncStepInitSql': 'Đang khởi tạo cơ sở dữ liệu SQLite...',
      'syncStepSaveLocal': 'Đang lưu dữ liệu cục bộ...',
      'syncStepComplete': 'Đồng bộ hóa hoàn tất!',
      'syncErrorMsg': 'Không tìm thấy UID đăng nhập.',
      'syncSnackbarError': 'Lỗi đồng bộ: {error}. Tiếp tục vào Home.'
    },
    'en': {
      'appName': 'Smart Note',
      'settingsTitle': 'Settings',
      'darkModeTitle': 'Dark Mode',
      'darkModeSubtitle': 'Toggle between light and dark mode',
      'languageTitle': 'Language',
      'languageSubtitle': 'Choose system display language',
      'biometricLockTitle': 'Biometric Lock',
      'biometricLockSubtitle': 'Use Fingerprint or Face ID to unlock notes',
      'biometricNotAvailable': 'Device does not support biometrics',
      'biometricNotEnrolled': 'Please enroll fingerprint in system settings',
      'biometricAuthFailed': 'Authentication failed. Try again?',
      'biometricAuthSuccess': 'Authentication successful',
      'biometricPromptReason': 'Authenticate to open note',
      'biometricLockedOut': 'Biometrics temporarily locked out due to many attempts',
      'biometricPermanentlyLockedOut': 'Biometrics permanently locked. Please unlock with PIN code',
      'biometricUnknownError': 'An error occurred during biometric authentication',
      'featureInDevelopment': 'Feature in development',
      'notificationsTitle': 'Notifications',
      'notificationsSubtitle': 'Manage notifications and reminders',
      'helpTitle': 'Help',
      'helpSubtitle': 'User manual and FAQs',
      'aboutTitle': 'About App',
      'aboutSubtitle': 'Version 1.0.0',
      'aboutDesc': 'Premium smart note application developed by Smart Note team. All data is secured and backed up to cloud safely.',
      'close': 'Close',
      'alertOk': 'OK',
      'alertCancel': 'Cancel',
      'toastThemeDark': 'Switched to dark appearance',
      'toastThemeLight': 'Switched to light appearance',
      'emptyHomeTitle': 'No notes yet',
      'emptyHomeSubtitle': 'Tap + to create your first note',
      'emptyArchiveTitle': 'Archive is empty',
      'emptyArchiveSubtitle': 'Archived notes will appear here',
      'emptyTrashTitle': 'Trash is empty',
      'emptyTrashSubtitle': 'Notes in trash will be deleted automatically after 7 days',
      'emptySearchTitle': 'No results found',
      'emptySearchSubtitle': 'Try another keyword',
      'emptySearchAction': 'Clear filter',
      'languageSelectTitle': 'Select Language',
      'notSetBiometricTitle': 'No biometrics set up',
      'notSetBiometricDesc': 'You need to add a fingerprint or face in your phone settings to use the note lock feature.',
      'notSetBiometricBtnLater': 'Later',
      'notSetBiometricBtnOpen': 'Open Settings',
      'settingsBiometricLockTitle': 'App Biometric Lock',
      'toastBiometricEnabled': 'Biometric lock enabled',
      'toastBiometricDisabled': 'Biometric lock disabled',

      // Drawer
      'drawerNotes': 'Notes',
      'drawerReminders': 'Reminders',
      'drawerLabels': 'Labels',
      'drawerEditLabels': 'Edit',
      'drawerCreateNewLabel': 'Create new label',
      'drawerArchive': 'Archive',
      'drawerTrash': 'Trash',
      'drawerSettings': 'Settings',

      // Home Screen
      'quickAudio': 'Audio',
      'quickImage': 'Image',
      'quickDrawing': 'Drawing',
      'quickList': 'List',
      'quickText': 'Text',
      'emptyRemindersTitle': 'No reminders',
      'emptyRemindersSubtitle': 'Notes with reminders will appear here',
      'emptyLabelTitle': 'Empty',
      'emptyLabelSubtitle': 'No notes in this label',
      'pinnedSection': 'Pinned',
      'othersSection': 'Others',
      'searchPlaceholder': 'Search',
      'searchRemindersPlaceholder': 'Search reminders',
      'searchInLabelPlaceholder': 'Search in {label}',
      'cancelSelection': 'Cancel selection',
      'selectedCount': '{count} selected',
      'changeLabel': 'Change labels',
      'pinUnpinBatch': 'Pin/Unpin notes',
      'archive': 'Archive',
      'moveToTrash': 'Move to trash',
      'sortUpdatedNewest': 'Sorting: Recently updated',
      'sortCreatedNewest': 'Sorting: Recently created',
      'sortTitleAZ': 'Sorting: Title A → Z',
      'assignLabelTitle': 'Assign labels',
      'createNewLabelHint': 'Create new label...',
      'createdAndAssignedLabel': 'Created and assigned label "{tag}"',
      'assignedLabel': 'Assigned label "{tag}"',
      'cancel': 'Cancel',
      'movedNotesToTrash': 'Moved {count} notes to trash',
      'undo': 'Undo',
      'archivedNotesCount': 'Archived {count} notes',

      // Trash Screen
      'deleteForeverTitle': 'Delete permanently?',
      'deleteForeverConfirm': 'This action cannot be undone. Are you sure you want to permanently delete {count} selected notes?',
      'delete': 'Delete',
      'trashWarning': 'Notes in the Trash will be deleted automatically after 7 days.',
      'trashTitle': 'Trash',
      'clearTrash': 'Empty Trash',
      'clearTrashInDevelopment': 'Empty feature is in development',
      'restore': 'Restore',
      'deleteForever': 'Delete forever',
      'restoreNote': 'Restore note',
      'restoredNote': 'Restored note',
      'deletingCloudNote': 'Permanently deleting cloud document...',

      // Archive Screen
      'restoredNotesCount': 'Restored {count} notes',
      'moveToTrashTitle': 'Move to Trash?',
      'moveToTrashConfirm': 'Are you sure you want to move {count} notes to the Trash?',
      'archiveTitle': 'Archive',
      'changeLayout': 'Change layout',
      'unarchive': 'Unarchive',
      'restoreToHome': 'Restore to Home',
      'unarchivedNote': 'Unarchived note',

      // Manage Labels Screen
      'editLabelsTitle': 'Edit labels',
      'createNewLabel': 'Create new label',

      // Search Screen
      'searchYourNotesHint': 'Search your notes',
      'noteTypeFilter': 'Note types',
      'listFilter': 'Lists',
      'imageFilter': 'Images',
      'audioFilter': 'Audios',
      'urlFilter': 'Links',
      'labelFilter': 'Labels',
      'statusFilter': 'Status',
      'foundNotesCount': 'FOUND {count} MATCHING NOTES',

      // Editor & Sheets
      'deleteNote': 'Delete note',
      'labels': 'Labels',
      'exportPdf': 'Export to PDF',
      'save': 'Save',
      'stay': 'Stay',
      'exit': 'Exit',
      'uploadingFilesTitle': 'Uploading files',
      'uploadingFilesConfirm': 'Files are currently being uploaded. If you exit now, the upload will be cancelled and files will not be saved. Are you sure you want to exit?',
      'pdfInitializing': 'Initializing PDF document...',
      'pdfDownloadingImages': 'Downloading attached images...',
      'pdfAttachedImages': 'Attached images:',
      'pdfPageCount': 'Page {page} / {total}',
      'pdfUntitledNote': 'Untitled Note',
      'pdfExportSuccess': 'Exported PDF successfully!',
      'pdfExportError': 'Error exporting PDF: {error}',
      'addImage': 'Add image',
      'addDrawing': 'Drawing',
      'startRecording': 'Record audio',
      'stopRecording': 'Stop recording',
      'addChecklist': 'Checklist',

      // Editor – upload/delete banners
      'uploadingAudio': 'Uploading audio...',
      'uploadAudioSuccess': 'Audio uploaded successfully!',
      'uploadAudioFail': 'Audio upload failed.',
      'uploadAudioError': 'Error: Audio upload failed.',
      'recordFailed': 'Recording failed: Could not retrieve audio file.',
      'deletingAudio': 'Deleting audio from cloud...',
      'deleteAudioSuccess': 'Audio deleted successfully.',
      'deleteAudioFail': 'Failed to delete audio.',
      'deletingImage': 'Deleting image from cloud...',
      'deleteImageSuccess': 'Image deleted successfully.',
      'deleteImageFail': 'Failed to delete image.',
      'uploadImageError': 'Error uploading image',
      'uploadDrawingError': 'Error uploading drawing',
      'updateDrawingError': 'Error updating drawing',

      // Editor – dialogs & snackbars
      'deleteNoteTitle': 'Delete note?',
      'deleteNoteConfirm': 'The note will be moved to Trash and deleted automatically after 7 days.',
      'archivedNote': 'Moved to archive',
      'unarchivedNoteMsg': 'Removed from archive',
      'lockedNote': '🔒 Note locked',
      'unlockedNote': '🔓 Note unlocked',
      'lockNoteTooltip': 'Lock note',
      'unlockNoteTooltip': 'Unlock note',
      'unpinTooltip': 'Unpin',
      'pinTooltip': 'Pin',
      'reminderTooltip': 'Reminder',
      'requiresSaveMsg': 'Please enter content to {action} this note',
      'aiTooltip': 'AI Assistant',
      'biometricRetry': 'Retry',

      // Editor – reminder sheet
      'reminderSheetTitle': 'Reminder',
      'scheduledTime': 'Scheduled time',
      'todayAt18': 'Today at 6:00 PM',
      'tomorrowAt8': 'Tomorrow at 8:00 AM',
      'nextMondayAt8': 'Next Monday at 8:00 AM',
      'pickDateTime': 'Pick date & time...',
      'reminderSet': '⏰ Reminder set for {time}',
      'reminderCancelled': '🚫 Reminder cancelled',
      'reminderPastError': '⚠️ Reminder time cannot be in the past!',
      'reminderPrefix': 'Reminder: {time}',
      'notifPermissionTitle': 'Notifications are disabled',
      'notifPermissionDesc': 'To not miss important note reminders, please grant notification permission in your phone settings.',
      'notifPermissionLater': 'Later',
      'notifPermissionOpen': 'Open Settings',
      'reminderToday': 'Today, {time}',
      'reminderTomorrow': 'Tomorrow, {time}',

      // Editor – lock screen
      'noteLockedTitle': 'Note is locked',
      'noteLockedSubtitle': 'Tap to unlock with biometrics',
      'authenticateNow': 'Authenticate now',

      // Editor – toolbar tooltips
      'toolbarAdd': 'Add',
      'toolbarColor': 'Color',
      'toolbarFormat': 'Format',
      'toolbarUndo': 'Undo',
      'toolbarRedo': 'Redo',
      'toolbarMore': 'More',

      // Editor – image source sheet
      'pickFromGallery': 'Choose from gallery',
      'takePhoto': 'Take photo',

      // Editor – title & note placeholder
      'titleHint': 'Title',
      'notePlaceholder': 'Note',

      // Editor – image viewer
      'imageCountTitle': '{current} of {total}',
      'drawOnImageTooltip': 'Draw on image',
      'imageOptionsTooltip': 'Image options',
      'duplicateImage': 'Duplicate',
      'deleteImage': 'Delete image',

      // Editor – label search
      'labelSearchHint': 'Enter label name',
      'createLabelOption': 'Create "{name}"',

      // AI Assistant
      'aiAssistantTitle': 'AI Note Assistant',
      'aiGenerateTitle': 'Generate title',
      'aiGenerateTitleSub': 'Auto-suggest a title from note content',
      'aiSummarize': 'Summarize note',
      'aiSummarizeSub': 'Create a concise summary from current content',
      'aiMakeChecklist': 'Convert to checklist',
      'aiMakeChecklistSub': 'Create a to-do list from current content',
      'aiSuggestLabels': 'Suggest labels',
      'aiSuggestLabelsSub': 'Suggest suitable labels for the note',
      'aiNeedContent': 'Please enter content before using AI',
      'aiNeedTitleOrContent': 'Please enter a title or content before using AI',
      'aiAlreadyChecklist': 'Note is already in checklist format',
      'aiNoChecklist': 'AI could not create a valid checklist',
      'aiCannotInsertInChecklist': 'Cannot insert summary while in checklist mode',
      'aiProcessing': 'AI is processing...',
      'aiSummaryTitle': 'Note summary',
      'aiSummaryInsert': 'Insert into note',
      'aiSummaryInsertText': '\n\nSummary:\n',
      'aiChecklistTitle': 'Checklist from AI',
      'aiUseChecklist': 'Use this checklist',
      'aiTitleSuggestTitle': 'AI title suggestion',
      'aiTitleProposed': 'Proposed title:',
      'aiUseTitle': 'Use this title',
      'aiTagsTitle': 'AI label suggestions',
      'aiTagsDesc': 'AI suggests the following labels. Please select the ones you want to use:',
      'aiAddLabels': 'Add labels',
      'aiNetworkError': 'AI needs a network connection. Please check your internet and try again.',
      'aiOverloadError': 'AI is overloaded. Please try again later.',
      'aiPermissionError': 'AI is not authorized. Please check your Firebase configuration.',
      'aiGenericError': 'AI could not process this request. Please try again.',

      // Drawing Screen
      'drawingBackgroundError': 'Error inserting background image: {error}',
      'selectColorWheel': 'Select custom color',
      'select': 'Select',
      'thickness': 'Stroke thickness: {val} px',
      'colorPalette': 'Color palette',
      'drawingSaveConfirmTitle': 'Save drawing?',
      'drawingSaveConfirmDesc': 'Do you want to save the changes to this drawing?',
      'discardExit': 'Discard and exit',
      'keepDrawing': 'Keep drawing',
      'saveDrawing': 'Save',
      'insertBackgroundImage': 'Insert background image',
      'paperTemplateStyle': 'Paper template style',
      'paperPlain': 'Plain paper',
      'paperRuled': 'Ruled paper',
      'paperGrid': 'Grid paper',
      'undoTooltip': 'Undo',
      'redoTooltip': 'Redo',

      // Profile Screen & Drawer
      'accountTitle': 'ACCOUNT',
      'profileTitle': 'Profile',
      'displayName': 'Display name',
      'bio': 'Bio',
      'bioHint': 'Write something about yourself...',
      'saveChanges': 'Save changes',
      'currentPassword': 'Current password',
      'newPasswordHint': 'New password (min 6 characters)',
      'confirmNewPasswordHint': 'Confirm new password',
      'update': 'Update',
      'changePassword': 'Change password',
      'personalInfo': 'Personal info',
      'manageAccountInfo': 'Manage account info',
      'securityTitle': 'Security',
      'passwordAndAuth': 'Password and auth',
      'logout': 'Sign out',
      'logoutConfirmTitle': 'Sign out?',
      'logoutConfirmDesc': 'Are you sure you want to sign out?',
      'userName': 'User',
      'manageAccountBtn': 'Manage account',
      'nameEmptyError': 'Name cannot be empty',
      'updateNameSuccess': 'Name updated ✓',
      'updateBioSuccess': 'Bio updated ✓',
      'fillAllFieldsError': 'Please fill all fields',
      'passwordLengthError': 'New password must be at least 6 characters',
      'passwordMismatchError': 'Confirm password does not match',
      'passwordChangeSuccess': 'Password changed successfully ✓',
      'oldPasswordIncorrectError': 'Old password incorrect',
      'avatarUpdateSuccess': 'Avatar updated ✓',
      'uploadError': 'Upload error: {error}',

      // Login & Syncing
      'welcomeBack': 'Welcome back!',
      'createNewAccount': 'Create new account',
      'loginToSync': 'Log in to continue syncing notes',
      'startSmartJourney': 'Start your smart note journey',
      'passwordLabel': 'Password',
      'forgotPassword': 'Forgot password?',
      'orContinueWith': 'Or continue with',
      'loginWithGoogle': 'Log in with Google',
      'noAccountQuestion': 'No account? ',
      'hasAccountQuestion': 'Already have an account? ',
      'registerNow': 'Register now',
      'loginNow': 'Log in',
      'networkConnectionError': 'No network connection. Please check again.',
      'fillEmailPassError': 'Please fill in Email and Password.',
      'syncingTitle': 'Syncing data',
      'pleaseWait': 'Please wait for a moment...',
      'syncStepCloud': 'Authenticating Cloud connection...',
      'syncStepFetch': 'Downloading notes from Firestore...',
      'syncStepInitSql': 'Initializing SQLite database...',
      'syncStepSaveLocal': 'Saving data locally...',
      'syncStepComplete': 'Sync completed!',
      'syncErrorMsg': 'Login UID not found.',
      'syncSnackbarError': 'Sync error: {error}. Continuing to Home.'
    }
  };

  static String translate(BuildContext context, String key) {
    try {
      final langProvider = Provider.of<LanguageProvider>(context);
      final lang = langProvider.languageCode;
      return _localizedValues[lang]?[key] ?? _localizedValues['vi']?[key] ?? key;
    } catch (e, stack) {
      debugPrint('AppLocalizations.translate error for key "$key": $e\n$stack');
      return _localizedValues['vi']?[key] ?? key;
    }
  }
}
